### ISSUE TITLE
SCMUtils Version: 2.7-  'analyzeScmRepository' command fails when run against EWM 7.0.1 iFix003

### ISSUE THREAD

**Issue by carl-payne** [jazz-community/ewm-scm-utils#1]
Attempting to use the 'analyzeScmRepository' command configured with the necessary augments for our EWM 7.0.1 staging server, but it fails with:

SCMUtils Version: 2.7
Executing Command analyzeScmRepository

Exception in thread "main" java.lang.ExceptionInInitializerError
at com.ibm.team.repository.client.TeamPlatform.getTeamRepositoryService(TeamPlatform.java:129)
at com.ibm.js.team.supporttools.framework.framework.AbstractTeamrepositoryCommand.execute(AbstractTeamrepositoryCommand.java:147)
at com.ibm.js.team.supporttools.framework.framework.AbstractCommand.run(AbstractCommand.java:73)
at com.ibm.js.team.supporttools.framework.AbstractSupportToolsFramework.execute(AbstractSupportToolsFramework.java:86)
at com.ibm.js.team.supporttools.scmutils.ScmSupportTools.main(ScmSupportTools.java:43)
Caused by: java.lang.NullPointerException
at org.eclipse.core.internal.runtime.InternalPlatform.getBundles(InternalPlatform.java:232)
at org.eclipse.core.internal.runtime.InternalPlatform.getBundle(InternalPlatform.java:222)
at org.eclipse.core.runtime.Platform.getBundle(Platform.java:1424)
at com.ibm.team.repository.client.internal.TeamRepositoryService.shouldAllowJtsLogin(TeamRepositoryService.java:80)
at com.ibm.team.repository.client.internal.TeamRepositoryService.<clinit>(TeamRepositoryService.java:66)
... 5 more

How do I resolve this ?, is the SCMUtils Version: 2.7 compatible with EWM 7.0.1 iFix003 ?

Please review and advise

**Comment by rsjazz** [comment]
There is no special compatibility built into the SCM tools. The Palain Java Client Libraries provided just need to work with the target EWM server version. I have used them mainly with 6.0.6.1, but other versions have worked too. I just ran (the 2.6 version) using the 6.0.6.1 plain java client libraries against the 7.0.1 server I have without any issue. I can and will not test all versions.

The error happens in a line
teamRepository = TeamPlatform.getTeamRepositoryService().getTeamRepository(repositoryURI);
with a nullpointer. Either the URI is null or, more likely the service call getTeamRepositoryService returns null. 

I do not know why this should happen. I would suggest trying a different plain Java Client libraries version, Java 1.8 version, or debug the program in Eclipse. With the information given, I can not provide more help.

**Comment by carl-payne** [comment]
Re-tested with RTC-Client-plainJavaLib-6.0.6.1 and encounter the same issue as when using EWM-Client-plainJavaLib-7.0.1

Can you advise a method of resolving this issue

**Comment by rsjazz** [comment]
If you paste the command line including parameters you use I can look at it. Other wise you have to run it in Eclipse in debug mode and look what happens. I have run this over and over and I have not seen that error, ever. I have certainly tested with 6.0.6.1.
